version: '3.9'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:
